# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lmr4rAsu4wmy8_N-6el7bzu9EBVuZYZ9

**Assigment--> 1**
"""

#Files-->TO store data in systematic order, data can be written , read and stored.
#Three modes are:Read,Write and Append.
#Open file
#r-->Read
myfile=open("saket.txt","r")
print(myfile.read())
#Close
myfile.close
#w-->Write
myfile=open('saket.txt',"w")
myfile.write("This is a lenovo laptop. \n")
myfile=open('saket.txt',"r")
print(myfile.read())
#a-->Append
myfile=open('saket.txt',"a")
myfile.write("This is not a lenovo laptop. \n")
myfile=open('saket.txt',"r")
print(myfile.read())
#Context manager-->manage unused files and data when not in use.
with open("saket.txt","r") as file1:
  print(file1.read())
mylines=["Hey \n","Hello\n","Good Evening"]
with open("saket.txt","w") as file1:
  file1.writelines(mylines)
with open("saket.txt","r") as file1:
  print(file1.read())