# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lmr4rAsu4wmy8_N-6el7bzu9EBVuZYZ9

**Assigment--> 1**
"""

#Examples of diffferent types of datatypes.
#Fundamental datatypes.
#String
x="Hello"
y=" World!"
z=x+y
print(z)
print('Hello World!')
print("Hello World!")
print('''Hello World!''')
print(type(z))
#Integer
x=10
y=20
z=x+y
print(z)
a=int(input("Enter the 1st number"))
b=int(input("Enter the 2nd number"))
c=a+b
print(c)
print(type(z))
#Float
xdde=10.1
y=20
z=x+y
print(z)
a=float(input("Enter the 1st number"))
b=float(input("Enter the 2nd number"))
c=a+b
print(c)
print(type(c))
#Boolean
x=10
y=20
z=x>y
print(z)
x=10
y=20
z=x<y
print(z)


#Collection datatypes.
#List[]
mylist=[1,2,3,"a","b",True]
print(len(mylist))
print(len(mylist))
mylist.insert(-3,10)
print(mylist)
print(type(mylist))
mylist.append(1)
print(mylist)
mylist.remove(1)
print(mylist)
mylist.pop()
print(mylist)
mylist1=[100,200,"furniture"]
mylist.extend(mylist1)
print(mylist)
del mylist[2]
print(mylist)
#Tuple()
mytuple=(10,20,"hey",False)
print(mytuple)
#Dictionary{}
mydic={"username":"admin","password":123,"color":"Red"}
print(mydic)
print(mydic['username'])
print(mydic['color'])
#Updating the value of key in dictionary.
mydic["password"]=99;print(mydic)
#adding value in dictionary.
mydic["fruit"]="apple";print(mydic)
#A key can hold more than value but that values will store in list.
mydic.pop('color')
del mydic
#Set{}
myset={1,2,7,9,3,5,"hello",6,False}
print(myset)
print(myset)
#Add
myset.add("okay")
print(myset)
set1={1,3,4,5,"fggh"}
set2={4456,456,4561,3,456}
#union()
unionset=myset.union(set1,set2)
print(unionset)
#Intersection-->Give common values.
set3=set1.intersection(set2)
print(set3)
#clear
set3.clear()
print(set3)